version: '3.9'
services:
  mysql_db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tododb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build: ./backend
    container_name: todo_node_app
    restart: unless-stopped
    ports:
      - "8000:4000"
    environment:
      DB_HOST: mysql_db
      DB_USER: user
      DB_PASSWORD: userpass
      DB_NAME: tododb
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql_db
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "9000:80"
    environment:
      PMA_HOST: mysql_db
      PMA_USER: user
      PMA_PASSWORD: userpass
    depends_on:
      - mysql_db
volumes:
  mysql_data:
